[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "uglyGui" 
version = "1.0"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}